logging:
  level:
    org:
      springframework:
        web: DEBUG
    ru:
      any:
        auth: DEBUG
spring:
  mvc:
    log-request-details: true
  application:
    name: any-auth-service
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/any_db?currentSchema=any_auth
    username: any_super_user
    password: admin123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    change-log: classpath:/db/changelog/database_any_auth_changelog.xml
    liquibase-schema: any_auth

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 60000
#        loggerLevel: BASIC

red:
  sms:
    login: GCompany
    api_key: RDdTABTskqyGQvjKjZMqapND
    route: sms
    from: GCompany
    url: https://cp.redsms.ru/api/message
    message_template: Код для авторизации в сервисе GCompany

jwt:
  secret:
    access: zb0PgJPfMku7GlESjSWt
    refresh: pKUlyyFEA7spPg1rRLkf