logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  mvc:
    log-request-details: true

sms:
  center:
    url: https://smsc.ru/sys/send.php
    login: Rocky-po
    psw: Pass_000_worD

jwt:
  secret:
    access: supermegasecret
    refresh: supermegarefreshsecret