apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: any-authenticate-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: any-authenticate-service.ru
      http:
        paths:
          - backend:
              serviceName: any-authenticate-service
              servicePort: 80