apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: any-authenticate-service-ingress
spec:
#  ingressClassName: ingress-nginx
  rules:
    - http:
        paths:
          - path: /any-authenticate-service
            pathType: Prefix
            backend:
              service:
                name: any-authenticate-service
                port:
                  number: 8080