name: Deploy to kubernetes

on:
  workflow_dispatch:
    inputs:

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check secrets
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Delete old deployment
        continue-on-error: true
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete deploy any-authenticate-service

      - name: Deploy app
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create -f ./deploy/deployment.yaml

      - name: Check deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pod -o wide

      - name: Delete old service
        continue-on-error: true
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete svc any-authenticate-service

      - name: Create service
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create -f ./deploy/service.yaml

      - name: Check service creating
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get svc -o wide